# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lone Star Lhurgoyfs
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Lonestar Lhurgoyfs - A group of Texas-based Magic players focusing on beer, Vintage, and Legacy, in that order.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://LoneStarLhurgoyfs.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: TexasLhurgoyfs
#github_username:  jekyll

# Build settings
markdown: kramdown
#theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
email:	sam@lonestarlhurgoyfs.com
subtitle: "Here for the beer."
url: https://lonestarlhurgoyfs.com
lang: en
author: Lone Star Lhurgoyfs
copyright:      "&#x2117; &amp; &#xA9; 2017-2018"
google_analytics: UA-98795844-1

permalink: :year-:month-:day-:title/
plugins:
  - jekyll-redirect-from
  - jekyll-feed